### ISSUE TITLE
Add First Install Error Instructions to FAQ

### ISSUE THREAD

**Issue by seniorm0ment** [t-e-l/tel#12]
there was an error, I forget what but it happens on a fresh TEL install. I believe  (could be wrong) it was fixed by

`apt update`
`apt upgrade`
`termux-change-repo`
select grimler repo 

I suggest adding this to the faq/wiki.

**Comment by v1nc** [comment]
Thanks for your feedback, this is fixed with the next update.  
Btw use `pkg` instead of `apt`: http://wiki.termux.com/wiki/Package_Management
