### ISSUE TITLE
Doesnt install

### ISSUE THREAD

**Issue by Vixeliz** [t-e-l/tel#15]
**Problem description**
When trying to install the latest version of tel i just get an error that says "app could not be installed"

**Steps to reproduce**
Try to install tel on android 11

**Expected behavior**
TEL to install

**Additional information**
Im on a samsung s21 ultra 5g running android 11

**Comment by seniorm0ment** [comment]
Ensure you are using the correct apk for your device.
Also ensure you removed Termux and all it's addons before installing as previously mentioned.

**Comment by v1nc** [comment]
Closing the issue because of inactivity, please specify the problem if it still persists.
