### ISSUE TITLE
[FEATURE] A command to whitelist an app for notification

### ISSUE THREAD

**Issue by codingotaku** [t-e-l/tel#4]
**Feature description**
It would be great to have a command that would let user pick which app to display notification from.
Currently [get_notifications.py#L37](https://github.com/t-e-l/tel/blob/725585b2e8063bfd617cd89d9cdb9a27a7decb78/bootstrap/changes/tel/.tel/scripts/status_manager/get_notifications.py#L37) contains a list of packages.

Instead of this we can pick up app list from a file (like `~/.notify_app_list`).

And as a bonus, a couple of commands to get along with it `notifs --add <package|app> [optional color]` and `notifs --remove <package|app>`

The reason I want this is because of the annoying **check termux-api permissions** message in the status when there are no notifications.

I was using TEL and got stuck with *check termux-api permissions* for a while until I saw this file. 
As a person who use only the telegram messenger from that list I get close to 0 notifications when I launch the App.

**Comment by SealedJoy** [comment]
can confirm this will be availible in next update! currently implemented as a list at '~/.tel/configs/notifications/ignored_pkgs' also added ignored_strings list so user can choose to block a string from specific notifications or the whole app. color picking and commands are non-existent yet but will see what i can do :)

**Comment by v1nc** [comment]
Added in the latest updated.
