### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by kisamat** [t-e-l/tel#8]
Tel it's a interesant launcher for Linux, but in Android 11, Not work fine.
They will make an update to solve this Problem? 

Thanks

**Comment by v1nc** [comment]
We are currently working on android 11 support. It will be included in the next update.

**Comment by kisamat** [comment]
Thanks, interesting project

**Comment by wardrich** [comment]
@v1nc Any word on when the update will arrive?  Really looking forward to giving this launcher a try.

**Comment by v1nc** [comment]
> @v1nc Any word on when the update will arrive? Really looking forward to giving this launcher a try.

We are planning to release the next update at the start of June.

**Comment by v1nc** [comment]
Android 11 is fully supported with the latest updated.
